### ISSUE TITLE
[FEATURE] /watch Route's Thumbnail values

### ISSUE THREAD

**Issue by Arthi-chaud** [zoriya/Kyoo#103]
**Is your feature request related to a problem? If yes, please describe.**
The /watch/{slug} route provides information about an item.
If the item is an Episode, we get additional data about next/previous episode if there's one.
Among that data, we get the url of the thumbnail of that Episode.
However, the url of the thumbnail of the current Episode is the parent Series', not the Episode's.

**Describe the feature you'd like**
We should be able to get, at least, the thumbnail of the current episode. Having the parent's thumbnail isn't a problem.

**Describe alternatives you've considered**
Build the route to the episode's thumbnail by hand

**Comment by AnonymusRaccoon** [comment]
Also include links for videos and subtitles.
