### ISSUE TITLE
Parse weird items name (scanner), especially anime names

### ISSUE THREAD

**Issue by zoriya** [zoriya/Kyoo#241]
### Feature description

The scanner should be able to parse things like:
`Shingeki no kyoshin season 4 part 2 special 2` (why are you like this tho)

I think an external database for that would be needed, I know thexem.info, not sure if this is applicable.

**Comment by zoriya** [comment]
Reopenning for complexe names like:
Owarimonogatari S2 E15.mkv
JoJo's Bizarre Adventure - Diamond is Unbreakable - 12.mkv

**Comment by Arthi-chaud** [comment]
'Scooby Doo Where Are You (1969)'
