### ISSUE TITLE
Parse external subtitles

### ISSUE THREAD

**Issue by zoriya** [zoriya/Kyoo#253]
### Feature description

The scanner should be able to retrieves external subtitles files and the /info of the trancoder should list them as well (maybe the scanner can ignore them and the transcoder could just check for them?)

**Comment by JeWe37** [comment]
It would also be nice if this supported subtitle titles, languages and tags(sdh, cc, hi, forced, default) like [jellyfin](https://jellyfin.org/docs/general/server/media/external-files/). MKS file support would also be helpful for bypassing potentially long subtitle extraction times poorly muxed larged files.
