### ISSUE TITLE
Rls vs Guessit?

### ISSUE THREAD

**Issue by cchance27** [zoriya/Kyoo#376]
### Feature description

Just wondering how Guessit compares vs Rls (https://github.com/moistari/rls) for parsing the video files, have you tried comparing?

**Comment by zoriya** [comment]
I never tried it, but it does seem less battle tested than guessit and the documentation is nonexistent. I actually implement some custom behaviors on top of guessit for some specific issues in parsing or better handling for thexem overrides (those rules can be found there https://github.com/zoriya/Kyoo/blob/master/scanner/scanner/parser/rules.py).
