### ISSUE TITLE
Auto-generate an AUTHENTICATION_SECRET

### ISSUE THREAD

**Issue by zoriya** [zoriya/Kyoo#380]
### Feature description

Right now, we ask users to create a `AUTHENTICATION_SECRET` but it needs to be manually changed for security and needs to be at least 256 chars (else there is an error that is not even handled now).
This should be done automatically.

**Comment by bo0tzz** [comment]
In Immich, we used to use JWTs for authentication and we had this same issue where people did not change the secret value, or changed it to an inappropriate value, resulting in these security issues. We found that we didn't actually need any of the features that JWTs offer, and so we moved to just using bog-standard random session tokens that we store in postgres. I'm not entirely familiar with your architecture, but at first glance it looks to me like that could be an appropriate approach for you as well?

**Comment by zoriya** [comment]
That could be an appropriate fix, but I'm thinking of generating a secret and storing it in db/file to persist it. That would be easier to implement
