### ISSUE TITLE
Provide alternate image registry to dockerhub

### ISSUE THREAD

**Issue by onedr0p** [zoriya/Kyoo#381]
### Feature description

Hi 👋🏼 Awesome project here...

Dockerhub has aggressive pull rate limits, it would be awesome if you could push the image to Github Container Registry (GHCR) too.

Dockerhub was one of the best years ago... GHCR is completely free for open source projects. It's also nice in that it integrates into your repo under the packages section. Take a look at my project [here](https://github.com/onedr0p/exportarr) and look at the packages on the right side.

Thanks!

**Comment by zoriya** [comment]
That should not be too hard, probably just editing the `docker.yml` workflow file I guess. If you want to make a PR for that, I'm open about having both dockerhub and ghcr.

**Comment by onedr0p** [comment]
@zoriya this should be it, thanks! https://github.com/zoriya/Kyoo/pull/383
