### ISSUE TITLE
support scan webdav

### ISSUE THREAD

**Issue by playingapi** [zoriya/Kyoo#390]
### Feature description

can mount webdav, and scan content of webdav

**Comment by zoriya** [comment]
can you explain how you want to use webdav with kyoo?

I'm not that familiar with the protocol but if I'm not mistaken it does the same job as a ftp. Can't you just mount your webdav and bind it to kyoo's volume?

**Comment by wowdd1** [comment]
many net disk have webdav access, but do not allow Read and write frequently, but scan need Read and write frequently,
can Kyoo implement emby 's [strm file](https://emby.media/support/articles/Strm-Files.html) function?  so do not need frequently access the net disk , and can scan the fake file(strm file) to get the metadata about the video file

the [alist](https://github.com/alist-org/alist) project can mound a lot  of net disk services,  and it have a [webdav interface ](https://alist.nn.ci/guide/webdav.html) to access it's content, 

so can Kyoo can read the alist content via webdav protocol to access a lot of net disk services, and use  strm file to can the files to get the video's metadata

strm is something like file soft link on linux, it point the the real video file, so do not need access the real video file to get the metadata

**Comment by playingapi** [comment]
many net disk have webdav access, but do not allow Read and write frequently, but scan need Read and write frequently,
can Kyoo implement emby 's [strm file](https://emby.media/support/articles/Strm-Files.html) function?  so do not need frequently access the net disk , and scan the fake file(strm file) to get the metadata about the video file

the [alist](https://github.com/alist-org/alist) project can mound a lot  of net disk services,  and it have a [webdav interface ](https://alist.nn.ci/guide/webdav.html) to access it's content, 

so can Kyoo can read the alist content via webdav protocol to access a lot of net disk services, and use  strm file to scan the files to get the video's metadata

strm is something like file soft link on linux, it point the the real video file, so do not need access the real video file to get the metadata

**Comment by zoriya** [comment]
The scanner only reads the FS when performing a full scan. After the full scan, it simply monitors fs events (file created/deleted).
Video files are not actually read before playing or manually asking for their metadata.

Kyoo has also no write permissions on the media's library.

I believe you can already mount webdav using something like [davfs2](https://wiki.archlinux.org/title/Davfs2).

With that said I still think that strm should be supported but I can't find a specification. I saw that vlc and kodi support it.

**Comment by playingapi** [comment]
it is more simple not more flexible,  do not need config,  type command, no need vps for some people
