### ISSUE TITLE
Scanner not detecting renamed folder

### ISSUE THREAD

**Issue by aziis98** [zoriya/Kyoo#412]
### Kyoo's version

4.4.0

### What happened?

Kyoo had a problem recognizing a folder with a non standard name so I tried to manually clean it up by first symlinking the folder and then by renaming directly the folder. Both times Kyoo didn't detect the change, the only thing I noticed is that the scanner just logs about the deleted folder (I was watching all logs with `docker compose logs -t -f` to find the problem).

Maybe the watcher just subscribed to a subset of file system events?

P.S. By the way, congrats. Impressive project for just one person!

**Comment by zoriya** [comment]
The watcher only listens to file changes, so I can understand why the symlink didn't work, no clue for the rename. I'll look into it.

PS: Thanks!

**Comment by zoriya** [comment]
I looked at it, the fs does not give rename events ; only delete/create. For directories, it does the same. 
For a `mv video/test video/test2` (with test being a directory):
`{(<Change.added: 1>, './video/test3'), (<Change.deleted: 3>, './video/test')}`

Matching rename manually is impossible (see https://github.com/samuelcolvin/watchfiles/pull/202#issuecomment-1305436437 for more info on why) but basically doing something like `mv * test/` will have all added/deleted events on the same list so we have no way of mapping add/delete events for each file/directory.

We can't differentiate file/directory on delete events. I think the easiest fix for this issue will be to check directory add events and trigger a whole fs scan if the directory contains files. If it doesn't, it was probably created by a mkdir, if it does, it might have been a rename. This method might trigger unnecessary fs scan if a directory is created and a file is created/moved inside it quickly.
