### ISSUE TITLE
Request to Add Chinese Language Option

### ISSUE THREAD

**Issue by tardlk** [zoriya/Kyoo#422]
### Feature description

I am a user of your project and have been appreciating the features and services it offers. I noticed that currently, your project does not provide an option for Chinese language support. I would like to suggest considering adding Chinese as an optional language to your project.
Thank you very much for your time and consideration.

**Comment by zoriya** [comment]
I'd love that, but I do not speak Chinese. If this is of value to you, please consider contributing translations. 
You can create a translation by adding a two letter language .json file in the `front/translations` directory.  You can find a reference file [here](https://github.com/zoriya/Kyoo/blob/master/front/translations/en.json)

**Comment by zoriya** [comment]
Yes that's good! You just need to commit and PR this file. You can find the GitHub's guide on how to do that [here](https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project). If you have trouble, please ask for help here or on discord.

If you cannot do this, I can also create the PR for you.

**Comment by tardlk** [comment]
Very happy to provide assistance. I'm sorry, but I'm still learning how to use GitHub. Could you please create a pull request for me this time?

**Comment by zoriya** [comment]
Don't worry, it's great! Thanks for the help!
