### ISSUE TITLE
Synology 7.2 installation error

### ISSUE THREAD

**Issue by lovejc0821** [zoriya/Kyoo#439]
### Kyoo's version

4.4

### What happened?

![image](https://github.com/zoriya/Kyoo/assets/29045258/90bd88b5-82fa-489f-9066-75ec777d9b21)

Error response from daemon: NanoCPUs can not be set, as your kernel does not support CPU CFS scheduler or the cgroup is not mounted
At the same time, how should we map the local directory into it?

**Comment by lovejc0821** [comment]
我看别人安装3.8版本的能成功，一年前

**Comment by zoriya** [comment]
It seems your install does not support docker's cpu limits. I think kyoo would start if you remove the following line from the docker compose file.
```yml
cpus: 1.5
```

I'll try to fix the backend to make the default docker file not have this line.

PS: Please keep the issue tracker in English, I can't read Chinese.

**Comment by lovejc0821** [comment]
已解决，谢谢

**Comment by zoriya** [comment]
I don't feel confident in tackling this issue (remove cpu limit by default) quickly, I want to setup good logs/profiling tooling before (see #359). I added an issue to track specifically the cpu limit removal: #448.

I'll close this issue and keep it like that for other users that might face the same issue on synology for now.
