### ISSUE TITLE
Matcher Unhandled error due to folder structure

### ISSUE THREAD

**Issue by Intuinewin** [zoriya/Kyoo#440]
### Kyoo's version

master

### What happened?

Due to my folder structure, the matcher cannot identifysome of my episodes. It seems guessit is doing weird things.

This folder structure is managed automatically by Sonarr and I would prefer not to have to rename all my files :)

My folder structure:
```bash
[nix-shell:~/Kyoo]$ python scanner/matcher/parser/guess.py '/media/series/Demon Slayer - Kimetsu no Yaiba/Season 4/Demon Slayer - Kimetsu no Yaiba - S04E10 - Love Hashira Mitsuri Kanroji WEBDL-1080p.mkv'
{
    "title": [
        "Demon Slayer",
        "Kimetsu no Yaiba"
    ],
    "season": 4,
    "episode_title": "Demon Slayer",
    "alternative_title": "Kimetsu no Yaiba",
    "episode": 1,
    "source": "Web",
    "screen_size": "1080p",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

If I put the file without the show and season folders:
```bash
(venv)
[nix-shell:~/Kyoo]$ python scanner/matcher/parser/guess.py '/media/series/Demon Slayer - Kimetsu no Yaiba - S04E10 - Love Hashira Mitsuri Kanroji WEBDL-1080p.mkv'
{
    "title": "Demon Slayer - Kimetsu no Yaiba",
    "season": 4,
    "episode": 1,
    "episode_title": "Someone's Dream",
    "source": "Web",
    "screen_size": "1080p",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

Traceback:
```
ERROR:matcher.matcher:Unhandled error
Traceback (most recent call last):
File "/app/matcher/matcher.py", line 36, in identify
await self._identify(path)
File "/app/matcher/matcher.py", line 86, in _identify
episode = await self._provider.search_episode(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/providers/implementations/thexem.py", line 198, in search_episode
new_name, tvdb_id = await self._client.get_show_override("tvdb", name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/providers/implementations/thexem.py", line 84, in get_show_override
show_name = clean(show_name)
^^^^^^^^^^^^^^^^
File "/app/providers/implementations/thexem.py", line 21, in clean
s = s.lower()
^^^^^^^
AttributeError: 'list' object has no attribute 'lower'
```

**Comment by zoriya** [comment]
I did not know guessit could return lists for titles. Thanks for the detailed report, I'll fix it right away.

**Comment by Intuinewin** [comment]
Thanks for your fast reply @zoriya

After applying your patch I can give you another exemple of an episode that doesn't get imported correctly. 

`/media/series/Star Trek - Discovery/Season 4/Star Trek - Discovery - S04E03 - Choose to Live SDTV.mkv`

```
2024-04-28 10:41:42 INFO:matcher.matcher:Identied /video/Star Trek - Discovery/Season 4/Star Trek - Discovery - S04E03 - Choose to Live SDTV.mkv: MatchesDict({'title': ['Star Trek', 'Discovery'], 'season': 4, 'episode_title': 'Star Trek', 'alternative_title': 'Discovery', 'episode': 3, 'source': 'TV', 'container': 'mkv', 'mimetype': 'video/x-matroska', 'type': 'episode'})
2024-04-28 10:41:42 ERROR:matcher.matcher:Could not find episode 3 of season 4 of serie 253 (absolute: 82)
```

Here keeping the first element results in searching `Star Trek` in tmdb which is show 253. But the actual show is `Star Trek : Discovery` id 67198

I'm not sure if it could break others setup but why not giving guessit only the filename instead of the entire path?

Jellyfin tests for reference: https://github.com/jellyfin/jellyfin/blob/master/tests/Jellyfin.Naming.Tests/TV/EpisodePathParserTest.cs

**Comment by zoriya** [comment]
Using the filename gives the same result. Guessit thinks the - means an alternative title, and kyoo does not search based on alternative titles.
We use thexem to identify some alternative titles of value. For example, here is a custom rule:

	Example: "JoJo's Bizarre Adventure - Diamond is Unbreakable - 12.mkv"
	Default:
	```json
	{
	        "title": "JoJo's Bizarre Adventure",
	        "alternative_title": "Diamond is Unbreakable",
	        "episode": 12,
	}
	```
	Expected:
	```json
	{
	        "title": "JoJo's Bizarre Adventure - Diamond is Unbreakable",
	        "episode": 12,
	}
	```

I think the correct fix would be to first search multiples times and taking the first hit. Using something like this list: ["title - alternative_title", "title", "alternative_title"]. This might have an impact on scan time tho.

**Comment by zoriya** [comment]
It seems Medusa does this too: https://github.com/pymedusa/Medusa/blob/master/medusa/name_parser/rules/rules.py#L256
but they only search for the "title - alternative_title" combo. I'll push a change to use that instead of the first element only. Please report back if it worked or if we need fallbacks to single "title" search.

**Comment by Intuinewin** [comment]
Seems to be good for all the examples I gave, thank you! I still have many import issues I need to investigate 😭

**Comment by zoriya** [comment]
Please get back with them, for now some anime are badly passed (most part2 shows don't work). I know some others issues but the goal is to slowly fix them all.

For anime, I want to use anilist or something like that for better parsing but that's way harder than It should (look at issue #352 for more info).
