### ISSUE TITLE
Missing entries if season skipped

### ISSUE THREAD

**Issue by Eidenz** [zoriya/Kyoo#458]
### Kyoo's version

commit cd18ec1

### What happened?

So I built the image from the fix of #457, which fixed most missing anime series. But I'm still missing 4 shows which all have a thing in common:
I skipped a few seasons and only downloaded specific ones. So for instance, I only have `/video/Dr. Stone/Season 3/` and Kyoo complains about not finding seasons 1 and 2 and ends up not showing it at all.

**Comment by zoriya** [comment]
Can you show logs and an example complete filepath for one of your episodes?

**Comment by Eidenz** [comment]
I also seem to have mixed the IDs I saw in logs, the complaints about missing seasons is just complaints about other shows.
So my bad, it just seems to not find an absolute number for the episodes, continuation of previous issue I suppose.

`/video/Dr. Stone/Season 3/[Breeze] Dr. STONE - New World - 03 [1080p][AV1][multisub] (weekly).mkv`
`/video/Dr. Stone/Season 3/[Breeze] Dr. STONE - New World - S03E13 [1080p EAC-3 AV1][multisub][dual audio] (weekly).mkv`

![image](https://github.com/zoriya/Kyoo/assets/27901016/554c348c-435d-4f93-8422-0d2baaeec3eb)

**Comment by zoriya** [comment]
On TheMovieDb, the absolute group only contains 36 episodes (so first two seasons only). That's why It could not find the absolute number of the third season. I'll figure out a workaround to guess absolute numbers when they are partially given on moviedb.
