### ISSUE TITLE
WOL Supports

### ISSUE THREAD

**Issue by GamerClassN7** [zoriya/Kyoo#465]
### Feature description

Hello, first thank you for this awesome peace of software it is nice to see some competition for Jellyfin.

Second question is, would be possible to add feature that when user connect application would sen WOL packed to predetermine MAC in network ?

My use case is that NAS storage is Running many drives, and that are using quit a lot of power, but most of the time when no one is using the Kyoo it does need to be on at all since Kyoo is Running  on different more efficient (in terms of energy) HW. And waking up NAS by phone or PC is really uncomfortable.  (Doable YES) so i was thinking that would be nice if app notice that volume is not accessible it could sent WOL packet to wake up NAS  I think this would be a nice addition to this well Thought app.

Thank you for any answer :)

**Comment by zoriya** [comment]
How would kyoo know it needs to wake the nas? And what kind of message is needed to actually wake the device (I know the concept of WOL, but I don't know how it works).

Is there a similar feature on other media browsers, that I could refer to know what this feature might look like? At first look like that I think this might be out of scope for Kyoo, but I see the value of this.

Thanks for your kind words!
