### ISSUE TITLE
Seperate Libraies by content

### ISSUE THREAD

**Issue by Serph91P** [zoriya/Kyoo#474]
### Feature description

Would love to be able to choose betwenn content/libraies in frontend. Just like in plex or any other media server. Sometimes its realy hard to know what it is Or if there a series and movies with the same title. For Example One Piece.

This picture shows it quite well I think:

<img width="1648" alt="grafik" src="https://github.com/zoriya/Kyoo/assets/8904984/b54ea11f-a232-4509-bcde-1635c4fed18c">

**Comment by zoriya** [comment]
Yes, filters in general have not been implemented on the app but they are available on the backend.

I don't have a good design idea in mind to show all those filters, maybe something like anilist's?

Related: #248

**Comment by zoriya** [comment]
Fixed by #528
