### ISSUE TITLE
Transcoder: Handle Base64 path with slash

### ISSUE THREAD

**Issue by Arthi-chaud** [zoriya/Kyoo#551]
### Kyoo's version

v4.6.0

### What happened?

Some path converted to base64 contains slashes. Unfortunately, the router in the transcoder interprets what's after the slash as the quality to convert to.

One possible solution would be for the transcoder to accept url-encoded base64 strings (and update the front app to properly encode that value)

**Comment by zoriya** [comment]
I don't really like the idea of using non-standard systems like that. We could try to switch to another encoding standard instead. Or maybe there is a standard way of handling base64 in url/paths.

**Comment by zoriya** [comment]
Turns out the base64 spec took that into account and created a url form for base64
