### ISSUE TITLE
[FEATURE] Choose the Poster from file or URL using User interface

### ISSUE THREAD

**Issue by Arthi-chaud** [zoriya/Kyoo#57]
**Describe the feature you'd like**
When editing a show's metadata, we should be able to set a poster using a local file or a URL

**Describe alternatives you've considered**
The workaround is to manually move the poster to Extra/poster.jpe

**Comment by zoriya** [comment]
I don't plan on allowing metadata to be edited by the front. The API is open, so there could be an external tool to edit metadata manually, but I want to embrace a "no config/no manual edit needed" in the core
