### ISSUE TITLE
Completely creshes when trying to stream HDR content

### ISSUE THREAD

**Issue by felipemarinho97** [zoriya/Kyoo#575]
### Kyoo's version

kyoo_transcoder:4.6

### What happened?

When I hit the play button:
![image](https://github.com/user-attachments/assets/344d0203-5410-44f3-bcbe-5a70d508202a)
BOOOM!! everything explodes on the client side..

this is what I got by checking the logs:

```
transcoder-vaapi-1  | 2024/08/02 22:49:12 Running mediainfo for /video/Shogun.2024.S01.MULTI.2160p.WEB-DL.DV.HDR.H265-AOC/S01/Shōgun_S01E01_Anjin.mkv
transcoder-vaapi-1  | 2024/08/02 22:49:12 mediainfo for /video/Shogun.2024.S01.MULTI.2160p.WEB-DL.DV.HDR.H265-AOC/S01/Shōgun_S01E01_Anjin.mkv finished in 93.557µs
traefik-1           | 192.168.3.2 - - [02/Aug/2024:22:49:12 +0000] "GET /api/episode/shogun-s1e1?fields=nextEpisode,previousEpisode,show,watchStatus HTTP/1.1" 200 2188 "-" "-" 1119 "api@docker" "http://172.24.0.8:5000" 6ms
transcoder-vaapi-1  | panic: runtime error: invalid memory address or nil pointer dereference
transcoder-vaapi-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6d2216]
transcoder-vaapi-1  |
transcoder-vaapi-1  | goroutine 15102 [running]:
transcoder-vaapi-1  | github.com/zoriya/kyoo/transcoder/src.GetInfo.func1.1()
transcoder-vaapi-1  | 	/app/src/info.go:192 +0x136
transcoder-vaapi-1  | created by github.com/zoriya/kyoo/transcoder/src.GetInfo.func1 in goroutine 15023
transcoder-vaapi-1  | 	/app/src/info.go:182 +0x12f
trae

```

Maybe because it`s HDR or is just the special char at "Shōgun" ?

**Comment by zoriya** [comment]
This is indeed a bug with the special character (that is now fixed on master). 

I haven't noticed the latest release was this old! I want to finish what I'm working on before releasing but I'll try to release soon.

In the meantime, you can update to the `edge` version 

Thanks for your report and for using kyoo!

**Comment by felipemarinho97** [comment]
Hey @zoriya, the same issue happens when you try to play a file that does not exists. I am using the edge version.

Steps:
1. Scan lib
2. Delete a file
3. Try to play the file

**Comment by zoriya** [comment]
yeah the pink screen isn't the best error screen x)

going back would also be weird, we still need an error screen
