### ISSUE TITLE
[FEATURE] Launch a Scan/housekeeping task using User Interface

### ISSUE THREAD

**Issue by Arthi-chaud** [zoriya/Kyoo#58]
**Describe the feature you'd like**
From User interface, we should be able to execute a scan or housekeeping task

**Describe alternatives you've considered**
Going to '/api/task/housekeeping' and '/api/task/scan'

**Additional context**
Handy when a movie was just added, and we want it to be shown in Kyoo

**Comment by zoriya** [comment]
Fixed by listen to file changes
