### ISSUE TITLE
[BUG] When a video is not compatible with the player, a message should be displayed

### ISSUE THREAD

**Issue by Arthi-chaud** [zoriya/Kyoo#59]
**Describe the bug**
When a video takes too long to transmux/transcode, or is not compatible with Kyoo,  nothing hapens, and the user might wait.

**To Reproduce**
Play a heavy file, for example

**Expected Behavior**
When a video takes too long to transmux/transcode, or is not compatible with Kyoo, a message should warn the user.
**Environment:**
 - Platform macOs X
 - Prebuilt version from commit 'b8022a6'

**Comment by zoriya** [comment]
Fixed by #175
