### ISSUE TITLE
[BUG] Scrolling down to the bottom 

### ISSUE THREAD

**Issue by Arthi-chaud** [zoriya/Kyoo#64]
**Describe the bug**
When we scroll down to the bottom of the page before the rest of the movie list is loaded (very quickly, like when we know what show we want), the loading is interrupted, until we scroll up a little bit.

**To Reproduce**
Scroll down to Kyoo's main page very quickly, before the end of the list is loaded. 

**Expected Behavior**
We'd expect the list to load progressively, like it does when we scroll normally.

**Environment:**
 - Platform: macOS
 - Prebuilt version from commit 'b8022a6'

**Comment by zoriya** [comment]
Fixed by #145
