### ISSUE TITLE
[FEATURE] Support Posters embedded in File

### ISSUE THREAD

**Issue by Arthi-chaud** [zoriya/Kyoo#67]
**Describe the feature you'd like**
On show scan, just like it does with subtitles, export posters embedded in file

**Describe alternatives you've considered**
Using ffmpeg to export each poster manually

**Additional context**
With iTunes, the posters are not stored in a seperate jpg file, it embeds the poster within the file

**Comment by zoriya** [comment]
This is actually pretty uncommon to store posters on video's metadata and video files are not opened on library's scan anymore to speed things up, so this won't be implemented.
